/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    Todo: typeof import('./src/components/Todo.vue')['default']
    UiCheckbox: typeof import('./src/components/UiCheckbox.vue')['default']
    UiDeleteIcon: typeof import('./src/components/UiDeleteIcon.vue')['default']
    UiInput: typeof import('./src/components/UiInput.vue')['default']
  }
}
